title: Sophia Fox Homepage
description: The homepage and linktree of Sophia Fox in Las Vegas, NV
theme: just-the-docs

url: https://sophiafoxcodes.github.io

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
